# Generated by Django 3.2.9 on 2021-11-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_suggestion_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
